/* ACM PSU platform build.
 *
 * The public website is plain HTML and needs no build. The member and admin
 * portals are TypeScript, so this bundles every entry point in platform/pages/
 * into assets/js/app/<name>.js as a self-contained ES module.
 *
 * Build output IS committed to the repository. GitHub Pages publishes the repo
 * as-is, so a future committee that only edits HTML never has to run Node —
 * they only need `npm run build` when they change something under platform/.
 *
 *   npm run build     one-off
 *   npm run watch     rebuild on save
 */
import { build, context } from 'esbuild';
import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync, rmSync } from 'node:fs';
import { join } from 'node:path';

const WATCH = process.argv.includes('--watch');
const OUT_DIR = 'assets/js/app';
const PAGE_DIR = 'platform/pages';

/* ---------------------------------------------------------------------------
 * Public runtime configuration.
 *
 * Only values that are safe in a browser belong here. The Supabase anon key is
 * designed to be public — every table is protected by row level security, so
 * the key alone grants nothing. Service-role keys, Google credentials and the
 * Cloudflare token live in Supabase Edge Function secrets and never reach here.
 * ------------------------------------------------------------------------- */
function readEnvFile(path) {
    if (!existsSync(path)) return {};
    const out = {};
    for (const raw of readFileSync(path, 'utf8').split('\n')) {
        const line = raw.trim();
        if (!line || line.startsWith('#')) continue;
        const eq = line.indexOf('=');
        if (eq === -1) continue;
        out[line.slice(0, eq).trim()] = line.slice(eq + 1).trim().replace(/^["']|["']$/g, '');
    }
    return out;
}

function writeEnvModule() {
    const file = readEnvFile('.env.local');
    const pick = (key) => process.env[key] || file[key] || '';

    const url = pick('PUBLIC_SUPABASE_URL');
    const anon = pick('PUBLIC_SUPABASE_ANON_KEY');

    if (!url || !anon) {
        console.warn(
            '\n  ! PUBLIC_SUPABASE_URL / PUBLIC_SUPABASE_ANON_KEY are not set.\n' +
            '    The public website still works; the portal will show a setup notice.\n' +
            '    See docs/SETUP.md step 1.\n'
        );
    }

    mkdirSync(OUT_DIR, { recursive: true });
    writeFileSync(join(OUT_DIR, 'env.js'),
        '/* Generated by build.mjs — do not edit. Public values only. */\n' +
        'window.ACM_ENV = ' + JSON.stringify({
            supabaseUrl: url,
            supabaseAnonKey: anon,
            siteUrl: pick('PUBLIC_SITE_URL') || 'https://acmchapter-psu.github.io/acm-psu-website'
        }, null, 2) + ';\n'
    );
}

/* Code splitting names shared chunks by content hash, so editing any shared
 * module leaves the previous chunk behind. Clearing the directory first keeps
 * dead bundles from being committed and deployed forever. */
function clearOutput() {
    if (!existsSync(OUT_DIR)) return;
    for (const file of readdirSync(OUT_DIR)) {
        if (file.endsWith('.js') || file.endsWith('.js.map')) {
            rmSync(join(OUT_DIR, file));
        }
    }
}

const entryPoints = readdirSync(PAGE_DIR)
    .filter((f) => f.endsWith('.ts'))
    .map((f) => join(PAGE_DIR, f));

const options = {
    entryPoints,
    outdir: OUT_DIR,
    bundle: true,
    format: 'esm',
    target: ['es2022'],
    splitting: true,
    minify: !WATCH,
    sourcemap: WATCH ? 'inline' : false,
    logLevel: 'info',
    define: { 'process.env.NODE_ENV': JSON.stringify(WATCH ? 'development' : 'production') }
};

clearOutput();
writeEnvModule();

if (WATCH) {
    const ctx = await context(options);
    await ctx.watch();
    console.log('watching platform/ ...');
} else {
    await build(options);
    console.log(`built ${entryPoints.length} page bundles into ${OUT_DIR}/`);
}
