/* RETAINED AS REFERENCE DATA ONLY — not called by anything.
 *
 * setupPositionSheets(), the only caller, was removed with the rest of the
 * retired public registration flow. These rows are the ORIGINAL role
 * definitions and the live Positions spreadsheet has since drifted from them
 * (capacities and descriptions differ), so treat the sheet as authoritative.
 *
 * This file is kept only until the current sheet rows are seeded into Supabase
 * event_positions, as a cross-check that no role is missed in that migration.
 * Delete it once that is done.
 */
function defaultPositionRows() {
  return [
    [
      "JAM26-PRESENTER",
      "ACM Programming Jam 2026",
      "Workshop Presenter",
      "Deliver one approved preparation session using material created by the content team.",
      "Attend briefing|Rehearse the approved deck and demo|Present the session|Answer questions|Send delivery feedback",
      "Confident speaker|Working knowledge of the assigned topic|Available for rehearsal and session",
      "2-hour rehearsal + 90-minute session",
      3,
      "7 Sep 2026",
      "Requirements check; short audition if needed",
      "Open",
      true,
    ],
    [
      "JAM26-CURRICULUM",
      "ACM Programming Jam 2026",
      "Workshop Curriculum Writer",
      "Design the lesson plan and participant exercises for one workshop day.",
      "Define learning outcomes|Write lesson and exercises|Add facilitator notes|Review technical accuracy|Revise after rehearsal",
      "Technical writing|Full-stack development knowledge|Can teach concepts step by step",
      "4–6 hours per module",
      3,
      "5 Sep 2026",
      "Writing or technical sample review",
      "Open",
      true,
    ],
    [
      "JAM26-SLIDES",
      "ACM Programming Jam 2026",
      "Workshop Slide Designer",
      "Turn approved curriculum into a clear and consistent presentation deck.",
      "Apply ACM visual style|Lay out approved content|Create diagrams|Check readability|Export editable and final files",
      "Visual communication|Presentation software experience|Can follow a design system",
      "4–6 hours per deck",
      3,
      "7 Sep 2026",
      "Design sample review",
      "Open",
      true,
    ],
    [
      "JAM26-DEMO",
      "ACM Programming Jam 2026",
      "Technical Demo Builder",
      "Build reliable live examples and backup walkthrough assets for presenters.",
      "Implement approved demo|Prepare starter and final states|Test every step|Capture backup recording|Write presenter runbook",
      "Git, Firebase and web tooling|Independent debugging|Reproducible documentation",
      "5–8 hours per demo",
      3,
      "7 Sep 2026",
      "Technical sample review",
      "Open",
      true,
    ],
    [
      "JAM26-MENTOR",
      "ACM Programming Jam 2026",
      "Workshop Mentor",
      "Support guided practice without completing participant work for them.",
      "Support assigned group|Answer scoped questions|Use mentor guide|Record recurring issues|Escalate platform problems",
      "Patient communicator|Web debugging knowledge|Available for one workshop day",
      "Briefing + one 3-hour workshop",
      9,
      "10 Sep 2026",
      "Skills and availability check",
      "Open",
      true,
    ],
    [
      "JAM26-BRIEF",
      "ACM Programming Jam 2026",
      "Competition Brief Writer",
      "Write the participant-facing application requirements and acceptance criteria.",
      "Define required features|Separate required and optional scope|Write constraints|Check event feasibility|Prepare locked release copy",
      "Requirements writing|Understands web scope|Maintains confidentiality",
      "6–8 hours total",
      2,
      "5 Sep 2026",
      "Writing sample and organizer review",
      "Open",
      false,
    ],
    [
      "JAM26-CHANGE",
      "ACM Programming Jam 2026",
      "Change Request Designer",
      "Create and test the organizer-only mid-competition requirement.",
      "Design fair change|Test effort on sample project|Write release instructions|Prepare judge guidance|Keep content confidential",
      "Product requirements knowledge|Can assess implementation effort|Maintains confidentiality",
      "4–6 hours total",
      2,
      "7 Sep 2026",
      "Organizer review",
      "Open",
      false,
    ],
    [
      "JAM26-JUDGING",
      "ACM Programming Jam 2026",
      "Judging Rubric Coordinator",
      "Create measurable scoring criteria and coordinate consistent judging.",
      "Draft rubric|Set weights and tie-breaks|Prepare score sheets|Run judge calibration|Verify final totals",
      "Analytical and detail-oriented|Software evaluation knowledge|Available for judging",
      "5 hours preparation + judging",
      2,
      "10 Sep 2026",
      "Rubric exercise review",
      "Open",
      true,
    ],
    [
      "JAM26-RUNSHOW",
      "ACM Programming Jam 2026",
      "Run-of-Show Coordinator",
      "Own the timing and handoffs for workshops and competition day.",
      "Build minute-by-minute schedule|Brief speakers|Prepare announcements|Track timing live|Record deviations",
      "Excellent time management|Clear communicator|Available for assigned event blocks",
      "4 hours preparation + event coverage",
      2,
      "10 Sep 2026",
      "Organization and availability check",
      "Open",
      true,
    ],
    [
      "JAM26-PLATFORM",
      "ACM Programming Jam 2026",
      "Platform Support Engineer",
      "Prepare and monitor accounts, repositories, Firebase and deployment tooling.",
      "Test setup guide|Verify services and accounts|Monitor incidents|Maintain backups|Document fixes",
      "GitHub, Firebase, Vercel and DNS|Strong troubleshooting|Available during event",
      "6 hours preparation + event coverage",
      4,
      "10 Sep 2026",
      "Technical skills review",
      "Open",
      true,
    ],
    [
      "JAM26-CHECKIN",
      "ACM Programming Jam 2026",
      "Registration & Check-in Coordinator",
      "Verify participant records and operate event-day check-in.",
      "Review registrations|Resolve incomplete teams|Prepare attendance list|Run check-in|Escalate eligibility issues",
      "Organized|Careful with personal data|Available before event opening",
      "3 hours preparation + 2 hours event day",
      3,
      "10 Sep 2026",
      "Requirements and availability check",
      "Open",
      true,
    ],
    [
      "JAM26-COMMS",
      "ACM Programming Jam 2026",
      "Event Communications Writer",
      "Write announcements, reminders, live updates and the verified recap.",
      "Plan communications|Write participant reminders|Prepare event updates|Collect verified results|Draft recap",
      "Strong writing|Reliable response time|Can follow approval workflow",
      "2–3 hours per week",
      3,
      "10 Sep 2026",
      "Writing sample review",
      "Open",
      true,
    ],

    [
      "CTF3-CHALLENGE",
      "ACM/CyberTech CTF 3.0",
      "CTF Challenge Author",
      "Build one scoped challenge with a verified flag and solution path.",
      "Write specification|Build artifact or service|Set difficulty and points|Provide organizer solution|Fix review findings",
      "Knowledge of one CTF category|Reproducible documentation|Maintains flag confidentiality",
      "6–12 hours per challenge",
      8,
      "10 Oct 2026",
      "Challenge proposal and skills review",
      "Open",
      true,
    ],
    [
      "CTF3-QA",
      "ACM/CyberTech CTF 3.0",
      "Challenge Reviewer & Tester",
      "Independently solve and quality-check challenges before release.",
      "Test clean solve|Check unintended paths|Verify flag and scoring|Report ambiguity or leakage|Approve or return challenge",
      "CTF experience|Methodical testing|Maintains confidentiality",
      "3–5 hours per challenge",
      6,
      "14 Oct 2026",
      "Skills and conflict review",
      "Open",
      true,
    ],
    [
      "CTF3-INFRA",
      "ACM/CyberTech CTF 3.0",
      "CTF Infrastructure Engineer",
      "Deploy and monitor the scoreboard, challenge services and network.",
      "Prepare hosting|Deploy approved challenges|Test isolation|Monitor uptime and logs|Maintain backups",
      "Linux, containers and networking|Strong troubleshooting|Available for rehearsal and competition",
      "8 hours preparation + event coverage",
      4,
      "14 Oct 2026",
      "Technical interview or practical review",
      "Open",
      true,
    ],
    [
      "CTF3-SCOREBOARD",
      "ACM/CyberTech CTF 3.0",
      "Scoreboard Administrator",
      "Operate teams, scoring, submissions, hints and final standings.",
      "Configure teams and points|Test submissions|Release approved hints|Monitor anomalies|Export verified results",
      "Detail-oriented|Understands CTF scoring|Maintains organizer confidentiality",
      "4 hours preparation + full competition",
      2,
      "17 Oct 2026",
      "Organizer review",
      "Open",
      true,
    ],
    [
      "CTF3-WRITER",
      "ACM/CyberTech CTF 3.0",
      "Security Curriculum Writer",
      "Create the lesson and lab for one preparation workshop.",
      "Define outcomes|Write lesson and lab|Add facilitator notes|Review safe examples|Revise after testing",
      "Security knowledge in one domain|Technical writing|Responsible disclosure mindset",
      "5–8 hours per module",
      4,
      "10 Oct 2026",
      "Writing or technical sample review",
      "Open",
      true,
    ],
    [
      "CTF3-PRESENTER",
      "ACM/CyberTech CTF 3.0",
      "Security Workshop Presenter",
      "Deliver an approved security session; curriculum and slides are provided.",
      "Attend briefing|Rehearse approved deck and lab|Present module|Guide questions safely|Report delivery feedback",
      "Confident speaker|Knowledge of assigned domain|Available for rehearsal and workshop",
      "2-hour rehearsal + assigned session",
      4,
      "14 Oct 2026",
      "Requirements check; audition if needed",
      "Open",
      true,
    ],
    [
      "CTF3-ASSISTANT",
      "ACM/CyberTech CTF 3.0",
      "CTF Workshop Assistant",
      "Help participants complete labs within approved assistance boundaries.",
      "Support assigned room|Troubleshoot setup|Use facilitator guide|Escalate unsafe issues|Record common blockers",
      "Patient communicator|Basic web-security tooling|Available for assigned workshop",
      "Briefing + assigned session",
      8,
      "17 Oct 2026",
      "Skills and availability check",
      "Open",
      true,
    ],
    [
      "CTF3-RULES",
      "ACM/CyberTech CTF 3.0",
      "Rules & Participant Guide Editor",
      "Produce the final competition rules and operating guide.",
      "Edit eligibility and team rules|Document allowed actions|Clarify hints and submissions|Check platform consistency|Prepare approved copy",
      "Policy writing|Understands CTF fairness|Detail-oriented",
      "5–7 hours total",
      2,
      "14 Oct 2026",
      "Writing sample review",
      "Open",
      true,
    ],
    [
      "CTF3-SOLUTIONS",
      "ACM/CyberTech CTF 3.0",
      "Hints & Solutions Archivist",
      "Standardize organizer hints, intended solutions and public writeups.",
      "Collect author records|Normalize hints|Verify commands and flags|Remove secrets|Publish approved archive",
      "Technical editing|Basic CTF knowledge|Handles confidential material responsibly",
      "5 hours preparation + post-event pass",
      3,
      "17 Oct 2026",
      "Technical writing sample review",
      "Open",
      true,
    ],
    [
      "CTF3-RUNSHOW",
      "ACM/CyberTech CTF 3.0",
      "CTF Run-of-Show Coordinator",
      "Coordinate setup, check-in, opening, announcements, closing and awards.",
      "Build timeline|Brief station leads|Prepare announcements|Track incidents and timing|Coordinate closing",
      "Excellent organization|Calm under pressure|Available for full event",
      "4 hours preparation + full event",
      2,
      "17 Oct 2026",
      "Availability and organization check",
      "Open",
      true,
    ],
    [
      "CTF3-LOGISTICS",
      "ACM/CyberTech CTF 3.0",
      "Venue & Logistics Coordinator",
      "Prepare room, signage, power, connectivity and organizer supplies.",
      "Create venue checklist|Confirm equipment|Set up stations|Track supplies|Lead cleanup",
      "Reliable for setup|Checklist discipline|Can coordinate with venue contacts",
      "4 hours preparation + setup and closing",
      4,
      "17 Oct 2026",
      "Availability check",
      "Open",
      true,
    ],
    [
      "CTF3-MEDIA",
      "ACM/CyberTech CTF 3.0",
      "Event Photo & Video Recorder",
      "Capture organized footage for the recap and archive.",
      "Follow shot list|Record horizontal and vertical footage|Respect consent|Label files|Upload originals",
      "Available during event|Adequate phone or camera storage|Can transfer large files",
      "4 hours event day + 1 hour upload",
      3,
      "17 Oct 2026",
      "Equipment and availability check",
      "Open",
      true,
    ],

    [
      "HACK26-BRIEF",
      "ACM Club Hackathon — Term 261",
      "Hackathon Brief Writer",
      "Define the theme, requirements, constraints and expected submission.",
      "Draft problem statement|Define mandatory requirements|Set team rules|Write acceptance criteria|Prepare participant release",
      "Requirements writing|Understands hackathon scope|Maintains confidentiality",
      "6–8 hours total",
      2,
      "Open until filled",
      "Writing sample and organizer review",
      "Open",
      true,
    ],
    [
      "HACK26-CURRICULUM",
      "ACM Club Hackathon — Term 261",
      "Hackathon Curriculum Writer",
      "Create preparation lessons aligned with the approved brief.",
      "Define outcomes|Write lesson and exercise|Add facilitator notes|Review accuracy|Revise after rehearsal",
      "Technical writing|Knowledge of workshop topic|Can align content to requirements",
      "5–8 hours per module",
      3,
      "Open until filled",
      "Writing or technical sample review",
      "Open",
      true,
    ],
    [
      "HACK26-PRESENTER",
      "ACM Club Hackathon — Term 261",
      "Hackathon Workshop Presenter",
      "Deliver an approved session without creating its curriculum or slides.",
      "Attend briefing|Rehearse approved material|Deliver session|Answer questions|Send feedback to content team",
      "Confident speaker|Knowledge of assigned topic|Available for rehearsal and session",
      "2-hour rehearsal + assigned session",
      3,
      "Open until filled",
      "Requirements check; audition if needed",
      "Open",
      true,
    ],
    [
      "HACK26-MENTOR",
      "ACM Club Hackathon — Term 261",
      "Hackathon Mentor",
      "Guide teams during building time without building their projects.",
      "Attend briefing|Support assigned teams|Use guiding questions|Escalate rule or platform issues|Record blockers",
      "Patient communicator|Broad software experience|Available for mentor shift",
      "Briefing + one mentor shift",
      8,
      "Open until filled",
      "Skills and availability check",
      "Open",
      true,
    ],
    [
      "HACK26-JUDGING",
      "ACM Club Hackathon — Term 261",
      "Hackathon Judging Coordinator",
      "Create the rubric and coordinate consistent project evaluation.",
      "Draft criteria|Set weights and tie-breaks|Prepare score sheets|Calibrate judges|Verify totals",
      "Analytical|Project evaluation knowledge|Available for calibration and judging",
      "5 hours preparation + judging",
      2,
      "Open until filled",
      "Rubric exercise review",
      "Open",
      true,
    ],
    [
      "HACK26-RESOURCES",
      "ACM Club Hackathon — Term 261",
      "API & Resource Curator",
      "Vet approved APIs, datasets, tools, accounts and documentation.",
      "Collect resources|Verify access and licensing|Test setup|Organize participant links|Maintain backups",
      "Can evaluate technical tools|Strong documentation|Can test access",
      "5–7 hours total",
      3,
      "Open until filled",
      "Technical requirements check",
      "Open",
      true,
    ],
    [
      "HACK26-SUBMISSIONS",
      "ACM Club Hackathon — Term 261",
      "Submission & Demo Coordinator",
      "Operate project submission, demo order and judge handoffs.",
      "Define submission fields|Test submission flow|Track entries|Build demo order|Prepare judge handoff",
      "Highly organized|Comfortable verifying files and links|Available for demos",
      "4 hours preparation + demo window",
      3,
      "Open until filled",
      "Availability and organization check",
      "Open",
      true,
    ],
    [
      "HACK26-RUNSHOW",
      "ACM Club Hackathon — Term 261",
      "Hackathon Run-of-Show Coordinator",
      "Own registration, opening, checkpoints, submissions, judging and awards timing.",
      "Create detailed schedule|Brief leads and speakers|Track checkpoints|Coordinate announcements|Record changes",
      "Excellent time management|Clear communicator|Available for full event",
      "4 hours preparation + full event",
      2,
      "Open until filled",
      "Availability and organization check",
      "Open",
      true,
    ],
    [
      "HACK26-LOGISTICS",
      "ACM Club Hackathon — Term 261",
      "Hackathon Logistics Coordinator",
      "Prepare venue, equipment, signage, power, connectivity and supplies.",
      "Create venue checklist|Confirm room and equipment|Set up team areas|Track supplies|Lead cleanup",
      "Reliable for setup|Checklist discipline|Can coordinate with venue contacts",
      "4 hours preparation + setup and closing",
      4,
      "Open until filled",
      "Availability check",
      "Open",
      true,
    ],
  ];
}
